/**:
  ros__parameters:
    serial_name: "/dev/ttyCLAP"
    parse_type: "BINARY"
    baud_rate: 460800
    activate_ntrip: "true"
    ntrip_ip: "212.156.70.42"
    ntrip_user_name: "K0734151301"
    ntrip_password: "GzMSQg"
    ntrip_mount_point: "VRSRTCM31"
    ntrip_port: 2101
    # Topics
    clap_imu_data: "clap/clap_msgs/clap_imu"
    clap_ins_data: "clap/clap_msgs/clap_ins"
    imu_topic: "clap/ros/imu"
    nav_sat_fix_topic: "clap/ros/gps_nav_sat_fix"
    autoware_orientation_topic: "clap/autoware_orientation"
    twist_topic: "clap/ros/twist_with_covariance_stamped"
    odom_topic: "clap/ros/odom"
    ### Time System Selection 
    #   0 --> GPS Global Time 
    #   1 --> ROS Rclcpp System time     
    time_system_selection: 0

    ### ENU -> NED Transform Selection
    enu_ned_transform: "true"

    #Frame values
    gnss_frame: "GNSS_INS/gnss_ins_link"
    imu_frame: "GNSS_INS/gnss_ins_link"
    autoware_orientation_frame: "GNSS_INS/gnss_ins_link"
    twist_frame: "GNSS_INS/gnss_ins_link"

    debug: "true"